//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenApp.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Computador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Computador()
        {
            this.Ventas = new HashSet<Venta>();
        }
    
        public int ComputadorID { get; set; }
        public int NumeroProcesadores { get; set; }
        public string MarcaProcesador { get; set; }
        public string TamanoDiscoDuro { get; set; }
        public string TamanoMemoria { get; set; }
        public string Componentes { get; set; }
        public int TipoComputadorID { get; set; }
        public decimal Precio { get; set; }

        [JsonIgnore]
        public virtual TipoComputador TipoComputador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
